apiVersion: v1
kind: Pod
metadata: 
  name: voting-app-pod
  app: demo-votibg-app
spec: 
  container:
    - name: voting-app
      image: kodekloud/examplevotingapp_vote:v1
      port:
        - containerPort: 80
